Survival Models {data-navmenu="Survival Models"}
=====================================

Column {.tabset}
-------------------------------------------------


### Survival Analysis

The ***survival function***, also known as a survivor function or reliability function, is a property of 
any random variable that maps a set of events, usually associated with mortality or failure of 
some system, onto time. 

It captures the probability that the system will survive 
beyond a specified time.
<p>
#### Reliability function

* The term ***reliability function*** is common in engineering while the term survival function 
is used in a broader range of applications, including human mortality. 
* Another name for the survival function is the complementary cumulative distribution function.

#### Definition

Let $T$ be a continuous random variable with cumulative distribution function $F(t)$ on the interval $[0,\infty)$. 

Its survival function or reliability function is:

$$R(t) = P(T > t)$$

$$R(t) = \int_t^{\infty} f(u)\,du,.$$

$$R(t) =  1-F(t).$$



<h5> Properties of the Survival Function</h5>

* Every survival function $R(t)$ is monotonically decreasing, i.e. $R(u) \le R(t)$ for all $u &gt; t$.
* The time, t = 0, represents some origin, typically the beginning of a study or the start of operation of some system. 
* $R(0)$ is commonly unity but can be less to represent the probability that the system fails immediately upon operation.
* The survivor function is right-continuous.




### The Cox Proportional-Hazards Model

The most common model used to determine the effects of covariates on survival

$$ h_i(t)=h_0(t)exp(\beta_{1}x_{i1} + \beta_{2}x_{ik} + ... + \beta_{2}x_{ik} ) $$

It is a semi-parametric model:

The baseline hazard function is unspecified
The effects of the covariates are multiplicative
Doesn't make arbitrary assumptions about the shape/form of the baseline hazard function
The Proportional Hazards Assumption

Covariates multiply the hazard by some constant
e.g. a drug may halve a subjects risk of death at any time \( t \)
The effect is the same at any time point
Violating the PH assumption can seriously invalidate your model!



### The Survival Function (Survival curve)

\[ S(t)=Pr(T>t) \]

The Survival function (\( S \)) is the probability that the time of death (\( T \)) is greater than some specified time (\( t \))

It is composed of:

The underlying Hazard function (How the risk of death per unit time changes over time at baseline covariates)
The effect parameters (How the hazard varies in response to the covariates)



### Hazard Probability 

* In the medical world, doctors often want to understand which treatments help patients survive 
longer  and which have no effect at all (or worse). In the business world, the equivalent 
concern is when customers stop. 
* This is particularly true of businesses that have a well-defined beginning and end to the customer relationship subscription-based relationships. These relationships are found in a wide range of industries, such as insurance, communication, cable televisions, newspaper/magazine subscription, banking, and electricity providers in competitive 
markets. 
* The basis of survival data mining is the hazard probability, the chance that someone who has 
survived for a certain length of time (called the customer tenure) is going to stop, cancel, or 
expire before the next unit of time. 
* This definition assumes that time is discrete, and such 
discrete time intervals whether days, weeks, or months often fits business needs. By 
contrast, traditional survival analysis in statistics usually assumes that time is continuous.



