Continuous Random Variables {data-navmenu="Random Variables"}
====================================

Column {.tabset}
-------------------------------------------------------------

### Properties

#### Conditional Expectations 

If $X$ is a continuous random variable, while $Y$ remains a discrete variable, the conditional expectation is

\[{\displaystyle \operatorname {E} (X\mid Y=y)=\int _{\mathcal {X}}x\;f_{X}(x\mid Y=y)\,\mathrm {d} x,}\]
with the conditional density of $X$ given $Y = y$ defined as \[{\displaystyle f_{X}(x\mid Y=y)={\frac {f_{X,Y}(x,y)}{P(Y=y)}}}\] where $f_{X,Y}(x, y)$ is the joint density of $X$ and $Y$. 

<p>

If both $X$ and $Y$ are continuous random variables, then the conditional expectation is

\[{\displaystyle \operatorname {E} (X\mid Y=y)=\int _{\mathcal {X}}x\;f_{X\mid Y}(x\mid y)\,\mathrm {d} x,}\]
where \[{\displaystyle f_{X\mid Y}(x\mid y)={\frac {f_{X,Y}(x,y)}{f_{Y}(y)}}}\] where $f_{Y}(y)$ gives the density of $Y$.

-------------------------------------------------------------


#### Marginal Probability Density Function

Given two continuous random variables $X$ and $Y$ whose joint distribution is known, then marginal probability density function can be obtained by integrating the joint probability distribution over $Y$, and vice versa. That is

\[{\displaystyle f_{X}(x)=\int _{c}^{d}f(x,y)dy}\] and \[{\displaystyle f_{Y}(y)=\int _{a}^{b}f(x,y)dx}\]

\noindent where ${\displaystyle x\in [a,b]}$, and ${\displaystyle y\in [c,d]}$



### Worked Examples

<h3> Worked Example 1</h3>


A random variable $\LARGE X$ which can be used in certain circumstances as a model for claim sizes has cumulative distribution function
\[\LARGE F(x) = \begin{cases}
0 & \mbox{ where }  x < 0 \\ 
1 - \left(\frac{2}{(2+x)}\right)^3 & \mbox{ where }  x > 0 \\ 
\end{cases}
\]

<h4> Exercises </h4>

a.  Calculate the value of the conditional probability $\LARGE P(X > 3|X > 1)$. 


<h4> Solution </h4>

<strong><a href="https://youtu.be/uaYXtM0lHRY">Click here for demonstrated solution</a></strong>

------------------------------------

<h3> Worked Example 2</h3>

The random variable $\LARGE X$ has probability density function $\LARGE f(x)$ given by
\[\LARGE f(x) \;=\; kx^2 (1- x) , \qquad 0 \leq x \leq 1 \]

<h4> Exercises</h4>

a. Show that $\LARGE k = 12$.
b. Show that the mode of $\LARGE X$ is at $\LARGE x = 2/3$ and draw a graph of $\LARGE f(x)$.
c. Find the mean and variance of $\LARGE X$.
d. Find the cumulative distribution function of X and obtain the probability that $\LARGE X$
lies within one standard deviation of its mean.

<h4> Solution </h4>

<strong><a href="https://youtu.be/rodfSPYXdh8">Click here for demonstrated solution</a></strong>
