
Cumulant Generating Function {data-navmenu="Random Variables"}
====================================

Column {.tabset}
-------------------------------------------------------------




### Cumulant Generating Function 
 
The cumulants of a random variable $\large X$ are defined using the cumulant-generating function $C(t)$, which is the natural logarithm of the moment-generating function:

  \[ {\large C(t)=\log \operatorname {E} \left[e^{tX}\right].}\]

The cumulants $\kappa_n$ are obtained from a power series expansion of the cumulant generating function:
\[ {\large C(t)=\sum _{n=1}^{\infty }\kappa _{n}{\frac {t^{n}}{n!}}=\mu t+\sigma ^{2}{\frac {t^{2}}{2}}+\cdots .}\]

This expansion is a Maclaurin series, so the $n$-th cumulant can be obtained by differentiating the above expansion $n$ times and evaluating the result at zero:

\[{\large \kappa _{n}=K^{(n)}(0).} \]

### Worked Examples

The cumulant generating function of a random variable X is given by:
 \[C_X (t) = \log M_X (t) = 2\left[ (1\;-\;t)^{-10} \;-\;1\right]\]
where $M_X(t)$ is the moment generating function.

<h4> Exercises</h4>

Determine the mean and variance of the distribution of $\large X$. 

<h4> Solution </h4>

<strong><a href="https://youtu.be/_x3tv15tHgE">Click here for demonstrated solution</a></strong>


