---
title: "StatsResource"
output: 
  flexdashboard::flex_dashboard:
    theme: united
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r child = 'main/introduction.Rmd'}
```

```{r child = 'probabilitydistributions/PoissonDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/BinomialDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/GeometricDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/HypergeometricDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/BinomialDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/NegativeBinomial.Rmd'}
```

```{r child = 'probabilitydistributions/NormalDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/UniformDistribution.Rmd'}
```


```{r child = 'probabilitydistributions/ExponentialDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/GammaDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/LognormalDistribution.Rmd'}
```

```{r child = 'probabilitydistributions/WeibullDistribution.Rmd'}
```



```{r child = 'probabilitydistributions/ApproximatingDistributions.Rmd'}
```

```{r child = 'probabilitydistributions/CompoundDistributions.Rmd'}
```

```{r child = 'probabilitydistributions/MixedDistributions.Rmd'}
```

 	  	
 	  	
