Probability Formulas {data-navmenu="Tables and Formulas"}
==============================================================


Column {.tabset}
----------------------------------

### Probability

#### Conditional probability:
\begin{equation*}
	P(B|A)=\frac{P\left( A\text{ and }B\right) }{P\left( A\right) }.
\end{equation*}
	
	
\item Bayes' Theorem:
\begin{equation*}
	P(B|A)=\frac{P\left(A|B\right) \times P(B) }{P\left( A\right) }.
\end{equation*}


### Discrete Probability Distributions
	
#### Binomial probability distribution:
\begin{equation*}
			P(X = k) = ^{n}C_{k} \times p^{k} \times \left( 1-p\right) ^{n-k}\qquad \left( \text{where  }
			^{n}C_{k} =\frac{n!}{k!\left(n-k\right) !}. \right)
\end{equation*}
		
#### Poisson probability distribution:
\begin{equation*}
			P(X = k) =\frac{m^{k}\mathrm{e}^{-m}}{k!}.
\end{equation*}
		
### Continuous Probabilitu Distributions

#### Exponential probability distribution:
\begin{equation*}
			P(X \leq k) = \begin{cases}
				1-e^{- k/\mu}, & k \ge 0, \\
				0, & k < 0.
	\end{cases}\qquad \left( \text{where  }
		\mu = \frac{1}{\lambda}\right)
\end{equation*}







