
Binomial Distribution {data-navmenu="Discrete Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------
### Binomial Distribution


#### Binomial Experiment

A binomial experiment (also known as a Bernoulli trial) is a statistical experiment that has the following properties:

* The experiment consists of $n$ repeated trials.
* Each trial can result in just two possible outcomes. We call one of these outcomes a ***success*** 
and the other, a ***failure***.
* The probability of success, denoted by $p$, is the same on every trial.
* The trials are independent; that is, the outcome on one trial does not affect the outcome on other trials.
<p>

Consider the following statistical experiment. You flip a coin five times and count the number of times the coin lands on heads. This is a binomial experiment because:

* The experiment consists of repeated trials. We flip a coin five times.
* Each trial can result in just two possible outcomes : heads or tails.
* The probability of success is constant : 0.5 on every trial.
* The trials are independent; that is, getting heads on one trial does not affect whether we get heads on other trials.
<p>

* A binomial experiment with n trials and
probability $p$ of success will be denoted by
\[B(n, p)\]
* Frequently, we are interested in the \textbf{\emph{number of successes}} in a binomial experiment, not in the order in which they occur.
* Furthermore, we are interested in the probability of that number of successes.
<p>

The probability of exactly k successes in a binomial experiment B(n, p) is given by
\[ P(X=k) = P(k \mbox{ successes }) = \;^nC_k  \times p^{k} \times (1-p)^{n-k}\]


* X: Discrete random variable for the number of successes (variable name)
*$k$ : Number of successes (numeric value)

* $P(X=k)$ ``probability that the number of success is $k$".

* $n$ : number of independent trials
* $p$ : probability of a success in any of the $n$ trial.
* $1-p$ : probability of a failure in any of the $n$ trial.

### Binomial Distribution

<h5> The Binomial Probability Distribution </h5> 
A Quick Review of the Binomial Distribution

*  The number of independent trials is denoted $n$.
*  The outcome of interest is known as a ``Success".
*  The other outcome is known as a ``failure".  
*  Often the applications of these names is counter-intuitive, i.e. defective components being the ``success".
*  The probability of a `success' is $p$ 
*  The expected number of `successes' from $n$ trials is $E(X) = np$
*  The \texttt{binom} family of commands in \texttt{R} are what we use to compute necessary values.



#### Binomial Distribution : Probability Density Function}
A binomial experiment is one that possesses the following properties:

* The experiment consists of n repeated trials;

* Each trial results in an outcome that may be classified as a success or a failure (hence the name, binomial);

* The probability of a success, denoted by p, remains constant from trial to trial and repeated trials are independent.
<p>
The number of successes X in n trials of a binomial experiment is called a \textbf{\textit{binomial random variable}}.


#### Binomial Probability Formula

The probability of exactly k successes in a binomial experiment $Bin(n, p)$ is given by

\[ P(X=k) = P(k \mbox{ successes in ``n" trails }) = \;^nC_k  \times p^{k} \times (1-p)^{n-k}\]


* X: Discrete random variable for the number of successes (variable name)
* $k$ : Number of successes (numeric value)


*   k= 0, 1, 2, ... n
*    $P(X=k)$ ``probability that the number of success is $k$".

* $n$ : number of independent trials
* $p$ : probability of a success in any of the $n$ trial.
* $1-p$ : probability of a failure in any of the $n$ trial.
* ${^nC_k}$ is a combination value, found using the Choose operator.



### Binomial Distribution : Expected Value and Variance

#### Expectation and Variance
If the random variable X has a binomial distribution with parameters $n$
and $p$, we write
\[ X \sim Bin(n,p) \]
Only these two parameters are needed to determine the probability of an event.




* The expected value of $X$ is: \[\operatorname{E(X)} = n \times p \]
* The variance of $X$ is:
\[\operatorname{Var(X)} = n \times p \times (1-p) = n\times p \times q \]


 
* $p$ is the probability of success * $q$ is the probability of failure in a binomial trial
* $n$ is the number of independent trials 

***Interpretation:***
If $n=100$, and $p=0.25$, then the average number of successes will be 25.


### Example

<h4> Binomial Example 1<h4>
	
Suppose a die is tossed 5 times. What is the probability of getting exactly 2 fours?
	
<h5>Solution:</h5> 
This is a binomial experiment in which the number of trials is equal to 5, the number of successes is equal to 2, and the probability of success on a single trial is 1/6 or about 0.167. Therefore, the binomial probability is:
	
	\[P(X=2) = ^5C_2 \times (1/6)^2 \times (5/6)^3 = 0.161\]


### Videos

<h5> Binomial Distribution </h5>


* <a href="https://youtu.be/dRNSiG2Hzfo/">Binomial Distribution - Worked Example</a>


