Chi Square Test Statistics {data-navmenu="Chi Square Tests"}
===========================================================

Column {.tabset}
-----------------------------------

### Chi Square Test Statistics

For this test we used the chi-squared test statistic which is given by:


\[X^2 = \sum_{i=1}^{n} {(O_i - E_i)^2 \over E_i}\]


The Chi Square test tests a null hypothesis stating that the frequency distribution of certain events observed in a sample is consistent with a particular theoretical distribution. The events considered must be mutually exclusive and have total probability 1. A common case for this is where the events each cover an outcome of a categorical variable.


*  $X^2$ = the test statistic that asymptotically approaches a $\chi^2$ distribution.
*  $O_i$ = an observed frequency;
*  $E_i$ = an expected (theoretical) frequency, asserted by the null hypothesis;
*  $n $  = the number of possible outcomes of each event.



The chi-square statistic can then be used to calculate ap-value by comparing the value of the statistic to a chi-square distribution. 
The number of degrees of freedom is equal to the number of cells ``n'', minus the reduction in degrees of freedom, ``p''.


