

Chi Square Testing  {data-navmenu="Modelling Data"}
=============================================================================

Column
---------------------------------------------

### Chi Square Testing for Goodness of Fit

<h5> Testing Goodness of Fit</h5>


Contingency tables are used to examine the relationship between subjects’ scores on two categorical variables.

<h5>Chi square test of independence</h5>

If the columns are not contingent on the rows, then the rows and column frequencies are independent. The test of whether the columns are contingent on the rows is called the chi square test of independence. The null hypothesis is that there is no relationship between row and column frequencies.

<h5>Chi-Square Testing</h5>

* Expected Values under the null hypothesis (<a title="ChiSquare-ExpectedValues" href="https://dl.dropboxusercontent.com/u/6044937/IntroStats/PartH-Chi%20Square%20Expected%20Values.pdf" target="_blank">here</a>)</li>
* Chi-Square Exercise (<a title="Chi-SquareExercise" href="https://dl.dropboxusercontent.com/u/6044937/IntroStats/PartH-Chi%20Square%20Exercise.pdf" target="_blank">here</a>)</li>



<strong>Chi-Square Testing</strong>


* Chi Square Test- computing the expected values - <a href="https://dl.dropboxusercontent.com/u/6044937/IntroStats/PartH-Chi%20Square%20Expected%20Values.pdf" target="_blank">Here</a></li>
* Chi Square Exercise - <a href="https://dl.dropboxusercontent.com/u/6044937/IntroStats/PartH-Chi%20Square%20Exercise.pdf" target="_blank">Here</a></li>



<h5>Chi Square Test</h5>

* Computing the Chi-Square Test Statistic - <a href="https://youtu.be/O5ds4O8K8rQ">HERE</a>. </li>
* Determining the Chi-Square Critical Value - <a href="https://youtu.be/6B4uZY1Onzc">HERE</a>.  </li>
	
* Chi Square Worked Example Part 1 - <a href="https://youtu.be/7ZKSeyjKWvw">HERE</a></li>
* Chi Square Worked Example Part 2 - <a href="https://youtu.be/wV88ylsaxjw">HERE</a></li>


