
Binomial Distribution {data-navmenu="Discrete Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------
### Binomial Distribution


#### Binomial Distribution : Probability Density Function}
A binomial experiment is one that possesses the following properties:

\begin{enumerate}
* The experiment consists of n repeated trials;

* Each trial results in an outcome that may be classified as a success or a failure (hence the name, binomial);

* The probability of a success, denoted by p, remains constant from trial to trial and repeated trials are independent.
\end{enumerate}


\noindent 
The number of successes X in n trials of a binomial experiment is called a \textbf{\textit{binomial random variable}}.


\subsection*{Binomial Probability Formula}
The probability of exactly k successes in a binomial experiment $Bin(n, p)$ is given by
\[ P(X=k) = P(k \mbox{ successes in ``n" trails }) = \;^nC_k  \times p^{k} \times (1-p)^{n-k}\]


* X: Discrete random variable for the number of successes (variable name)
* $k$ : Number of successes (numeric value)


*   k= 0, 1, 2, ... n
*    $P(X=k)$ ``probability that the number of success is $k$".

* $n$ : number of independent trials
* $p$ : probability of a success in any of the $n$ trial.
* $1-p$ : probability of a failure in any of the $n$ trial.
* ${^nC_k}$ is a combination value, found using the Choose operator.



### Binomial Distribution : Expected Value and Variance

#### Expectation and Variance
If the random variable X has a binomial distribution with parameters $n$
and $p$, we write
\[ X \sim Bin(n,p) \]
Only these two parameters are needed to determine the probability of an event.




* The expected value of $X$ is: \[\operatorname{E(X)} = n \times p \]
* The variance of $X$ is:
\[\operatorname{Var(X)} = n \times p \times (1-p) = n\times p \times q \]


 
* $p$ is the probability of success * $q$ is the probability of failure in a binomial trial
* $n$ is the number of independent trials 

***Interpretation:***
If $n=100$, and $p=0.25$, then the average number of successes will be 25.




### Videos

<h5> Binomial Distribution </h5>


* <a href="https://youtu.be/dRNSiG2Hzfo/">Binomial Distribution - Worked Example</a>





### Formula

<h5> Formula Sheet </h5>

$$ [P(X = k) = $$

