Gamma Distribution {data-navmenu="Continuous Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------

### The Gamma Distribution


The gamma distribution can be parameterized in terms of a shape parameter $\alpha$ = k and an inverse scale parameter $\beta$, called a rate parameter.
A random variable X that is gamma-distributed with shape $\alpha$ and rate $\beta$ is denoted
\[
X \sim  \textrm{Gamma}(\alpha,\beta)
\]


{

\[\scriptstyle\mathbf{E}[ X] = \frac{\alpha}{\beta}\]


\[
\scriptstyle \operatorname{Var}[ X] = \frac{\alpha}{\beta^2}
\]
}

-------------------
By the central limit theorem, if $\alpha$ is large, then gamma distribution can be approximated by the normal distribution with mean and standard deviation\[\mu = \frac{\alpha}{\beta}\] 
\[\sigma=\frac{\sqrt{\alpha}}{\beta}\]


<h5>The Gamma Distribution</h5>


* <a href="https://youtu.be/YcT5aDjZ3sc/">	Gamma Distribution - Electricity Consumption Example	</a>	
* <a href="https://youtu.be/dh8gpsM7HpM/">	Gamma Random Variables - Normal Approximation	</a>	

### Worked Examples

<h5>Worked Example</h5>
In a certain Metropolitan city the daily consumption of electric power (in Million Kilowatt Hour (MKH)) may be regarded as a random variable having Gamma
distribution with parameter (3,2). 
<p>
If the power plant has a daily capacity of 12 MKH, what is the probability that this power supply will be inadequate on any given day.
<br>

<a href = "https://youtu.be/YcT5aDjZ3sc">Solution</a>

<hline>


### Skewness

<h5> Mode and Skewness: Worked Example</h5>

Consider the following measure of skewness for a unimodal distribution:

\[ S_{KP}  \;=\; \frac{ \mbox{mean} \;-\; \mbox{mode}}{ \mbox{ standard deviation} } \] 

a. Determine the value of $\normalsize{S_{KP}}$ for a gamma distribution with parameters $\alpha = 1.6$ and
$\lambda  = 0.2$. 
b. Comment on why $\normalsize{S_{KP}}$  is a suitable measure of skewness for distributions with one mode.

<a href = "https://youtu.be/Ty2i1Mx9GQo">Solution</a>



### Moment Generating Functions

<h5> Cumulant Generating Functions </h5>

Let $normalsize{X}$ be a random variable having a gamma distribution with mean $\normalsize{\alpha\lambda}$  and variance $\normalsize{\alpha\lambda^2}$  and let the $\normalsize{i}$-th cumulant of the distribution of $\normalsize{X}$ be denoted $\normalsize{\kappa_i}$.
<p>
Assuming the moment generating function of $\normalsize{X}$, determine the values of $\normalsize{\kappa_2}$, $\normalsize{\kappa_3}$ and $\normalsize{\kappa_4}$.
<p>
<strong>
<a href = "https://youtu.be/zgR496RKmMA">Solution</a>
</strong>

 
