
Negative Binomial Distributions {data-navmenu="Discrete Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------

### Introduction

Suppose there is a sequence of independent Bernoulli trials. 
Thus, each trial has two potential outcomes called success and failure. In each trial the probability of success is ${p}$ and of failure is (${1 - p}$). 

The Negative Binomial distribution refers to the probability of the number of times needed to do something until achieving a fixed number of desired results. For example:


* How many times will I throw a coin until it lands on heads for the 10th time?
* How many children will I have when I get my third daughter?
* How many cards will I have to draw from a pack until I get the second Joker?


Just like the Binomial Distribution, the Negative Binomial distribution has two controlling parameters: the probability of success p in any independent test and the desired number of successes m. If a random variable X has Negative Binomial distribution with parameters p and m, its probability mass function is:

\[P(X=n) = {n-1 \choose m-1} p^m (1-p)^{n-m} \mbox{, for } n \ge m.\]

### Type 1 Specficiation

This approach models the number of failures (denoted ${k}$) in a sequence of independent and identically distributed Bernoulli trials before a specified (non-random) number of successes (denoted ${r}$) occurs.
Then the random number of failures we have seen, ${X}$, will have the negative binomial (or Pascal) distribution:
\[  {\displaystyle X\sim \operatorname {NB} (r,p)}\]

<h4>Probability Mass Function</h4>
\noindent The probability mass function of the negative binomial distribution is

\[  {\displaystyle f(k;r,p)\equiv \Pr(X=k)={\binom {k+r-1}{k}}(1-p)^{r}p^{k}}\]
where $k$ is the number of failures, ${r}$ is the number of successes, and ${p}$ is the probability of success. 

<p>
<h5>Parameters</h5>

* Mean	${\displaystyle {\frac {pr}{1-p}}}$
* Variance	${\displaystyle {\frac {pr}{(1-p)^{2}}}}$

<p>

### Type 2 Specficiation

\noindent This approach models the number of trial (denoted $n$) in a sequence of independent and identically distributed Bernoulli trials before a specified (non-random) number of successes (denoted ${r}$) occurs. (N.B. $n = k + r$.)

<h4>Probability Mass Function</h4>

Let ${X}$ denote the number of trials until the ${r}$-th success. 
The probability mass function of the negative binomial distribution is
	
\[ {\textstyle f(n;r,p)\equiv \Pr(X=n)=} { {\binom {n-1}{r-1}}(1-p)^{n-r}p^{r}} \]
where $n$ is the number of trial, ${r}$ is the number of successes, and ${p}$ is the probability of success. 

<p>
<h5>Parameters</h5>


* Mean	${ {\frac {r}{p}}}$
* Variance	$ {\frac {r(1-p)}{p^{2}}}$


### Worked Examples

<h5> Negative Binomial Distribution: Worked Example</h5>

Suppose that in a group of insurance policies (which are independent as regards
occurrence of claims), 20\% of the policies have incurred claims during the last year.
An auditor is examining the policies in the group one by one in random order until
two policies with claims are found.

a. Determine the probability that exactly five policies have to be examined until
two policies with claims are found.

b. Find the expected number of policies that have to be examined until two
policies with claims are found.



* <a href = "https://youtu.be/P1-FtKFbrtU/">Solution</a>
