Poisson Distribution {data-navmenu="Discrete Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------


### Poisson Distribution

<h5> Poisson Distribution</h5>


#### Probability Density Function for the Poisson Distribution}
A discrete random variable $X$ is said to follow a Poisson distribution with parameter $m$, written $X \sim \mbox{Poisson}(m)$.




* Here the key parameter, the \textbf{Poisson Mean}, is the expected number of occurence per unit period. 
* It is usually denoted as either $m$ or $\lambda$.


\noindent Given the mean number of successes ($m$) that occur in a specified region, we can compute the Poisson probability based on the \textit{probability density function} formula.



\begin{framed}
\noindent \textbf{Poisson Formula}\\
The probability that there will be $k$ occurrences in a \textbf{unit time period} is denoted $P(X=k)$, and is computed as:
{
\large
\[ P(X = k)=\frac{m^k e^{-m}}{k!} \]
}

\noindent where




 
%\itemf(x) the probability of x occurrences in an interval. 
* $m$ (or $\lambda$) is the expected value of the mean number of occurrences in any interval (i.e. the Poisson mean),
* $e=2.718$,
* $k = 0, 1, 2, \ldots$,
* $m > 0$.



#### Poisson Expected Value and Variance}


If the random variable X has a Poisson distribution with parameter $m$, we write
\[ X \sim Poisson(m) \]
Note the expected number of occurrences per unit time is often denoted $\lambda$ (lambda) rather than $m$.

% If X is a Poisson distribution stochastic variable with parameter $\lambda$, then
% 
% 
% * The expected value $E[X]=\lambda$
% * The variance $Var[X]=\lambda$
% 





* Expected Value of X : $\mbox{E}(X)=  m \mbox{ or } \lambda$
* Variance of X : $\mbox{Var}(X) = m \mbox{ or } \lambda$
* Standard Deviation of X : $SD(X) = \sqrt{m} \mbox{ or } \sqrt{\lambda}$


\noindent Important 
\[ \mbox{E}(X) = \mbox{Var}(X)\]
* Poisson Distribution - Probability Mass Function
* <a href= "https://www.youtube.com/watch?v=nc4vErCoo0w">Confidence Intervals for Poisson Variables </a>


### Worked Examples

<h5>Worked Examples 1 </h5>

On the average 8 calls per hour are received in a telephone board. Assuming that the
number of calls received in the board in a given length of time is a Poisson process, find
the probability that


<h4>Exercises</h4>

a. 6 calls received in 2 Hours 
b. at least 2 calls in the next 20 minutes

<h4> Solution</h4>

<strong><a href="https://youtu.be/88xt7Bb5jJc">Click here for demonstrated solution</a></strong>


### Confidence Intervals for Poisson Random Variables

<h3> Worked Example 1</h3>

It is assumed that claims on a certain type of policy arise as a Poisson process with
claim rate $\lambda$ per year.


For a group of 150 independent policies of this type, the total number of claims during
the last calendar year was recorded as 123.
Determine an approximate 95\% confidence interval for the true underlying annual
claim rate for such a policy.

<h4> Solution</h4>

<strong><a href = "https://youtu.be/5r8JMrKSFrU/">Click here for demonstrated solution</a></strong>

---------------------------------------------

<h3> Worked Example 2</h3>

It is assumed that the numbers of claims arising in one year from motor insurance
policies for young male drivers and young female drivers are distributed as Poisson
random variables with parameters $ \lambda_m$ and $\lambda_f$ respectively.

Independent random samples of 120 policies for young male drivers and 80 policies
for young female drivers were examined and yielded the following mean number of
claims per policy in the last calendar year: $ x_m = 0.24$ and $\LARGE x_f = 0.15$ .

Calculate an approximate 95% confidence interval for $\LARGE \bar{x}_{m} - \bar{x}_{f}$ , the difference between
the respective Poisson parameters.

<h4> Solution</h4>

<strong><a href="https://youtu.be/mRQgWDoHCXg">Click here for demonstrated solution</a></strong>

--------------------

<h3> Videos </h3>

* <a href = "https://youtu.be/5r8JMrKSFrU/"> Confidence Intervals for Poisson Random Variables </a>
* <a href = "https://youtu.be/3Y3pJaLcXdc/"> Confidence Intervals for Poisson Random Variables </a>
* <a href = "https://youtu.be/nc4vErCoo0w/"> Confidence Intervals for Poisson Variables</a>
* <a href = "https://youtu.be/N291An2ui18/"> Poisson Random Variables Confidence Intervals For Difference In Rates </a>



### Goodness of Fit Tests

<h5> Goodness of Fit Tests</h5>

* <a href = "https://youtu.be/ABcBPTef_vE/">Poisson Random Variables: Chi Square for Poisson Distribution</a>





