Difference in proportions {data-navmenu="Inference Procedures"}
====================================================================

Column {.tabset}
-------------------------------------------------

Confidence Interval {data-navmenu="Difference In Proportions"}
====================================================================

Column {.tabset}
-------------------------------------------------


### Confidence Interval

### Testing the Difference Between Two Population Proportions

*  When we wish to test the hypothesis that the proportions in two populations are not different, the two sample proportions are pooled as a basis for determining the standard error of the
difference between proportions.

*  Note that this differs from the procedure used previously on statistical estimation, in which
the assumption of no difference was not made.

*  Further, the present procedure is conceptually similar to that presented in Section 11.1, in which the two sample variances are pooled as the basis for computing the standard error of the difference between means.




This procedure is used to compare two proportions from two different populations. For two tailed tests, the null hypothesis states that the population proportion $\pi_1-\pi_2$ has a specified value, with the alternative stating that  $\pi_1-\pi_2$ does not have this value. 



<h4> Specifying the Null and Alternative Hypothesis</h4>


\[H_0 : \pi_1 = \pi_2\]
\[H_1 : \pi_1 \neq \pi_2\]

\[H_0 : \pi_1 - \pi_2 = 0\]
\[H_1 : \pi_1 -  \pi_2 \neq 0\]




*  Expected Value of differences under null hypothesis: $\pi_1 - \pi_2 = 0$

*  Significance level = 0.01

\[SE(p_1 - p_2) = \sqrt{\bar{p}(1-\bar{p})\left( \frac{1}{n_1} + \frac{1}{n_2} \right)  }\]

*  Calculate Pooled Proportion Estimate

\[ \bar{p} = \frac{29 + 62}{1110 + 1553} \]

*  Test Statistic

\[ \frac{(p_1 - p_2) - (\pi_1 - \pi_2)}{SE(\pi_1 - \pi_2)} \]



The formula for the estimated standard error is:

\[ S.E (\hat{p}_1 - \hat{p}_2)  = \sqrt{\bar{p}(100- \bar{p}) \left( {1 \over n_1} + {1 \over n_2}  \right)} \]


where $\bar{p}$ is a aggregate proportion (proportion of successes from overall sample, regardless of which group they are in).

### Pooled Estimate for Population Proportion

The pooled estimate of the population proportion, based on the proportions obtained in two independent samples.





Worked Examples {data-navmenu="Difference In Proportions"}
====================================================================

Column {.tabset}
-------------------------------------------------




### Worked Example




<h4> Proportions : Remarks</h4>

*  Small Sample sizes will not be considered for the case of sample proportions or Difference of proportions. Small samples will considered for ``sample mean" cases only.

*  The computed p-values is compared to the pre-specified significance level of 5\%. Since the p-value ($<0.0001$) is less than the significance level of 0.05, the effect is statistically significant. 

*  Since the effect is significant, the null hypothesis is rejected. The conclusion is that the probability of graduating from high school is greater for students who have participated in the early childhood intervention program than for students who have not. 

*  The results could be described in a report as:
The proportion of students from the early-intervention group who graduated from high school was 0.86 whereas the proportion from the control group who graduated was only 0.52. The difference in proportions is significant, with $p < 0.0001$.


### Summary of Inference Procedures

<h4> Point Estimates:</h4>
\[\hat{p}_1 = \frac{x_1}{n_1}  \]
\[\hat{p}_2 = \frac{x_2}{n_2}  \]


<h5>Hypotheses:</h5>
\[H_0 : \qquad \pi_1 \leq \pi_2   \]
\[H_1 : \qquad \pi_1 > \pi_2   \]


*  The population proportion for group 1 does not exceed the corresponding value for group 2. 
*  The population proportion for group 1 does exceed (is greater than) the corresponding value for group 2.


\[H_0 : \qquad \pi_1 - \pi_2  \leq 0  \]
\[H_1 : \qquad \pi_1 - \pi_2 > 0   \]

<h4> Critical Value</h4>

*  $\alpha = 0.05$
*  One-tailed Procedure (refer back to $H_1$) k=1
*  Large sample ($x_1+x_2 > 30$)


<h4> Descision}
is $|TS| > CV$?

Conclusion: We can reject the null hypothesis, We can reasonably conclude that....




<h4> Difference in proportions<h4>
This lesson describes how to construct a confidence interval for the difference between two sample proportions, p1 - p2.




<h4> Standard Error for Difference of Proportions<h4>

\[S.E. (\hat{P}_1 - \hat{P}_2)  = \sqrt{ [P_1 \times (1 - P_1) / n_1] + [P_2 \times (1 - P_2) / n_2] } \] 

* $\hat{P}_1$ and $\hat{P}_2$ are the sample proportions of groups 1 and 2 respectively.
* $n_1$ and $n_2$ are the sample sizes of groups 1 and 2 respectively.



* SE = $\sqrt{ [p_1 \times (1 - p_1) / n_1] + [p_2 \times (1 - p_2) / n_2] } $
* SE = $\sqrt{ [0.40 \times 0.60 / 400] + [0.30 \times 0.70 / 300] } $
* SE  = $\sqrt{[ (0.24 / 400) + (0.21 / 300) ]}$ = $\sqrt{(0.0006 + 0.0007)}$ = sqrt(0.0013) = 0.036 
