Dixon Q-Test for Outliers {data-navmenu="Testing Model Assumptions"}
=====================================

Column {.tabset}
-------------------------------------------------


### Dixon Q-Test for Outliers

<h5>Dixon Q-Test for Outliers</h5>

Use the Dixon Q-Test to determine whether or not there is an outlier value present in this data set.
(Use a 5% significance level).




\[ \{19, 36,33,  25, 30, 28, 31,36, 29, 37\}\]

<p>
--------------------------------------------------

*  Arrange the data set into ascending order.

\[ \{ 19, 25, 28, 29, 30, 31, 33, 36, 36, 37\} \]

*  Here the potential outlier is the lowest value, i.e. 19


--------------------------------------------

<h4> Hypotheses</h4>

We can formally state the null and alternative hypothesis as follows


* [H$_0$] There are no outliers present in the data.
* [H$_1$] There is one outlier present (i.e. the lowest value 19)


--------------------------------------------

<h4> Test Statistic</h4>

*  The test statistic for this procedure is as follows:

\[ Q_{TS} =  \frac{\mbox{Gap}}{\mbox{Range}} \]

*  The gap is the difference of the outlier from the next value. In this case , the next value is 25, so the gap is 
\[ \mbox{Gap} = 25 - 19 = 6\]
*  The range is simply the difference between the maximum and minimum value.
\[ \mbox{Range} = 37-19 =18\]

*  \[ Q_{TS} =  \frac{\mbox{Gap}}{\mbox{Range}} = \frac{6}{18} =0.333 \]


*  Before we look at the critical value, we confirm the size of the data set is $n=10$.

*   The critical value can be determined from the following table. 

* The column to chose is the significance level (here 5\% or 0.05 ). The row to use is $n$, the number of items in the data set.

-----------

\begin{tabular}{|c|c|c|c|}
\hline
$n$	&	$\alpha=0.10$	&	$\alpha=0.05$	&	$\alpha=0.01$	\\ \hline
3	&	0.941	&	0.970	&	0.994	\\ \hline
4	&	0.765	&	0.829	&	0.926	\\ \hline
5	&	0.642	&	0.710	&	0.821	\\ \hline
6	&	0.560	&	0.625	&	0.740	\\ \hline
7	&	0.507	&	0.568	&	0.680	\\ \hline
8	&	0.468	&	0.526	&	0.634	\\ \hline
9	&	0.437	&	0.493	&	0.598	\\ \hline
10	&	0.412	&	0.466	&	0.568	\\ \hline
11	&	0.392	&	0.444	&	0.542	\\ \hline
12	&	0.376	&	0.426	&	0.522	\\ \hline
13	&	0.361	&	0.410	&	0.503	\\ \hline
14	&	0.349	&	0.396	&	0.488	\\ \hline
15	&	0.338	&	0.384	&	0.475	\\ \hline

\end{tabular} 


```{r echo=FALSE, warning=FALSE}
library(knitr)
knitr::kable(head(iris))
```


#### Decision Rule



*  If the Test Statistic is greater than the Critical value, reject the null hypothesis
\[ Q_{TS} > Q_{CV}\]

*  Otherwise we fail to reject the null hypothesis

### Worked Example

<h4> Worked Example </h4>
Consider the data set:

\[0.189,\ 0.167,\ 0.187,\ 0.183,\ 0.186,\]\[ 0.182,\ 0.181,\ 0.184,\ 0.181,\ 0.177 \,\]

<h5> Solution</h5> 
 
* <a href="https://youtu.be/C0KltVEk6c8">  Click here for Demonstration</a> 




-------------------------------------------------------------


#### Step 1: Hypotheses for the Dixon Test.


$H_0$ No Outlier Present in Data
$H_1$ There is an Outlier present in Data (You may identify it)

<p>
------------------------------
#### Step 2: Dixon Q Test Statistic

To apply a Q test for suspicious data, arrange the data in order of increasing values and calculate Q as defined:

\[ Q = \frac{\text{gap}}{\text{range}} \]

Where gap is the absolute difference between the outlier in question and the closest number to it. 

<p>
------------------------------

Consider the data set:

\[0.189,\ 0.167,\ 0.187,\ 0.183,\ 0.186,\]\[ 0.182,\ 0.181,\ 0.184,\ 0.181,\ 0.177 \,\]

Now rearrange in increasing order:

\[0.167,\ 0.177,\ 0.181,\ 0.181,\ 0.182,\]\[ 0.183,\ 0.184,\ 0.186,\ 0.187,\ 0.189 \, \]


We hypothesize 0.167 is an outlier (based on it's large gap to next number, i.e. 0.010). 
<p>
------------------------------
#### Test Statistic

Calculate The Test Statistic $Q_{Ts}$:
\[ Q_{TS}=\frac{\text{gap}}{\text{range}} = \frac{0.177-0.167}{0.189-0.167}=0.455.\]
<p>
------------------------------
#### Critical Value

* Choose the Critical Value based on sample size and significance level $\alpha$. \smallskip
* In this table we work on the basis of confidence level. \smallskip \item Let's use 95\% as our confidence level. \\ (i.e. 5\% significance, i.e. $\alpha=0.05)$ 

#### Step 4 : Dixon Q Test: Decison Rule

* If $Q_{TS} > Q_{CV}$ , where $Q_{CV}$ is a critical value corresponding to the sample size and confidence level, then reject the null hypothesis. 
*  If $Q_{TS} \leq Q_{CV}$ , we fail to reject. null hypothesis. i.e. Not enough evidence. \smallskip

* At 95\% confidence, $Q_{TS} \leq Q_{CV}$ i.e $ 0.455 \leq 0.466$ 
* Therefore we dont have enough evidence to classify the lowest value 0.167 as an outlier. 




