Hypothesis Testing {data-navmenu="Hypothesis Testing"}
====================================================================

Column {.tabset}
-------------------------------------------------





### The Critical Value

*   The critical value(s) for a hypothesis test is a threshold to which the value of the test statistic in sample is compared to determine whether or not the null hypothesis is rejected.
*   We will use the initials CV for the sake of brevity.*   The critical value for any hypothesis test depends on the significance level at which the test is carried out, and whether the test is one-sided or two-sided.
*   The critical value is determined the exact same way as quantiles for confidence intervals; using Murdoch Barnes table 7.


### Determining the Critical value
*   A pre-determined level of significance $\alpha$ must be specified. Usually it is set at 5\% (0.05).*   The number of tails must be specified, either one tailed or two tailed, i.e. $k$ is either 1 or 2.*   Sample size is an issue. We must decide whether to use $n-1$ degrees of freedom or $\infty$ degrees of freedom, depending on the sample size in question.*   The manner by which we compute critical value is identical to the way we compute quantiles. 

### Critical value

A critical value is any value that separates the critical region ( where we reject the null hypothesis) for that tha values of the test statistic 
that do not lead to a rejection of the null hypothesis.

#### Critical Region 
	
Remark: The absolute value function of some value x is denoted $|x|$. It is the magnitude of the value without consideration of whether the value is positive or negative.
	
	
	
*   Let TS denote Test Statistic and CV denoted Critical Value.
*   $|TS| > CV$ Then we reject null hypothesis.
*   $|TS| \leq CV$ Then we \textbf{fail to reject} null hypothesis.
*   Suppose TS = 2.99, CV = 1.96
*   For our die-throw example; TS = 2.99, CV = 1.96.
*   Here $|2.99| > 1.96$ we reject the null hypothesis that the die is fair.
*   Consider this in the context of ``proof". 

 The critical region ( or rejection region ) is the set of all values of % the test statistic that causes us to reject the null hypothesis.




### One Way ANOVA in Experimental Design



<h5>One Way ANOVA</h5>

### p-values
