
Statistical Process Control {data-navmenu="Special Topics"}
=======================================
  
column {.tabset}
------------------------------

### Statistical Process Control

Statistical process control (SPC) is a method of quality control which uses statistical methods. SPC is applied in order to monitor and control a process. Monitoring and controlling the process ensures that it operates at its full potential. At its full potential, the process can make as much conforming product as possible with a minimum (if not an elimination) of waste (rework or trash).

SPC can be applied to any process where the “conforming product” (product meeting specifications) output can be measured. Key tools used in SPC include control charts; a focus on continuous improvement; and the design of experiments. An example of a process where SPC is applied is manufacturing lines.

<strong>Notes</strong>

* Statistical Process Control Definitions – <a title="SPCDefns" href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-Definitions.pdf" target="_blank">Here</a>
* Control Charts – <a href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-ControlCharts.pdf" target="_blank">Here</a>
* Control Charts – Worked Example – <a title="SPC control charts " href="https://dl.dropboxusercontent.com/u/6044937/SPC%20and%20IndStats/SPC%20Control%20Charts%20Example.pdf" target="_blank">Here</a>
* WECO Tests – <a title="WECO tests" href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-WecoTests.pdf" target="_blank">Here</a>
* Control Charts – Control Limits – Worked Example –<a title="SPC Control" href="https://dl.dropboxusercontent.com/u/6044937/SPC%20and%20IndStats/SPC%20Worked%20Example%202.pdf" target="_blank">Here</a>
* CUSUM Charts – <a title="CUSUM" href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-CUSUM.pdf" target="_blank">Here</a>
* Process Capability – <a title="SPC-PC" href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-ProcessCapability.pdf" target="_blank">Here</a>
* Process Capability Indices – <a title="PCIndices" href="https://dl.dropboxusercontent.com/u/6044937/Stats2/SPC-CapabilityIndices.pdf" target="_blank">Here</a>



### Attribute Data
  
Attribute data is also known as "count" data. Typically, we will count the number of times we observe some condition (usually something we do not like, such as an error) in a given sample from the process. This is different from measurement data in its resolution.

Attribute data has less resolution, since we only count if something occurs, rather than taking a measurement to see how close we are to the condition. For example, Attributes data for a health care process might include the number of patients with a fever, whereas Variables data for the same process might be the measurement of the patient temperature.

Thus, Attributes data generally provides us with less information than measurement (variables) data would for the same process. Thus, for attributes data, we will generally not be able to predict if the process is trending towards an undesirable state, since it is already in this condition.

#### Summary

* Attribute data is purely binary in nature. Good or Bad, Yes or No. No analysis can be performed on attribute data.

* Attribute data must be converted to a form of Variable data called discrete data in order to be counted or useful.

* Attribute data is qualitative data that can be counted for recording and analysis.

* Examples include the presence or absence of a required label, the installation of all required fasteners.

* Attribute data is not acceptable for production part submissions unless variable data cannot be obtained.

* The control charts based on attribute data are percent chart, number of affected units chart, count chart, count-per-unit chart, quality score chart and demerit chart.


### Control Charts

The control chart is a graph used to study how a process changes over time. Data are plotted in time order. A control chart always has a central line for the average, an upper line for the upper control limit and a lower line for the lower control limit. These lines are determined from historical data. By comparing current data to these lines, you can draw conclusions about whether the process variation is consistent (in control) or is unpredictable (out of control, affected by special causes of variation).
<p>
Control charts for variable data are used in pairs. The top chart monitors the average, or the centering of the distribution of data from the process. The bottom chart monitors the range, or the width of the distribution. If your data were shots in target practice, the average is where the shots are clustering, and the range is how tightly they are clustered. Control charts for attribute data are used singly.
<p>
<h2>When to Use a Control Chart</h2>

* When controlling ongoing processes by finding and correcting problems as they occur.
* When predicting the expected range of outcomes from a process.
* When determining whether a process is stable (in statistical control).
* When analyzing patterns of process variation from special causes (non-routine events) or common causes (built into the process).
* When determining whether your quality improvement project should aim to prevent specific problems or to make fundamental changes to the process.

<span style="text-decoration: underline;"><strong>References</strong></span>

Nancy R. Tague’s <a href="http://asq.org/quality-press/display-item/index.html?item=H1224" target="_blank" rel="noopener">The Quality Toolbox</a>, Second Edition, ASQ Quality Press, 2004, pages 155-158.



#### Run Charts

Run Charts are basic trend charts that may be used with both variables (data that is both quantitative and continuous in measurement, such as a measured dimension or time) and attributes (count) data. The Run chart monitors the process location over time. Run Charts are NOT control charts, as they do not have statistical control limits. For that reason, they may not be used to establish statistical control of a process or to measure process capability.
<p>
<strong>When to Use a Run Chart</strong>

Run Charts are sometimes used when there is insufficient data to properly analyze a process using statistical control charts. They should never be used in place of control charts, and cannot offer the benefits of control charts (mainly that of ascertaining whether a process is in a state of statistical control, or to determine process capability).<p>
The x-axes are time based, so that the charts show a history of the process. For this reason, you must have data that is time-ordered; that is, entered in the sequence from which it was generated.<p>
Run Charts typically use three of the standard eight Western Electric / Nelson Run Tests Rules. These three rules provide a broad indication of process stability, but by themselves lack the sensitivity of statistical control charts.

### Attribute Data



Attribute data is also known as "count" data. Typically, we will count the number of times we observe some condition (usually something we do not like, such as an error) in a given sample from the process. This is different from measurement data in its resolution. 
<p>
Attribute data has less resolution, since we only count if something occurs, rather than taking a measurement to see how close we are to the condition. For example, Attributes data for a health care process might include the number of patients with a fever, whereas Variables data for the same process might be the measurement of the patient temperature.
<p>
Thus, Attributes data generally provides us with less information than measurement (variables) data would for the same process. Thus, for attributes data, we will generally not be able to predict if the process is trending towards an undesirable state, since it is already in this condition.
<p>
<h4>Summary</h4>

* Attribute data is purely binary in nature. Good or Bad, Yes or No. No analysis can be performed on attribute data.
* Attribute data must be converted to a form of Variable data called<h4> discrete data</h4> in order to be counted or useful.
* Attribute data is qualitative data that can be counted for recording and analysis.
* Examples include the presence or absence of a required label, the installation of all required fasteners.
* Attribute data is not acceptable for production part submissions unless variable data cannot be obtained.
* The control charts based on attribute data are percent chart, number of affected units chart, count chart, count-per-unit chart, quality score chart and demerit chart.


