Game Theory {data-navmenu="Game Theory"}
=======================================

Column {.tabset}
---------------------------  
  
### Game Theory

<h5> Game Theory </h5>

Game theory is the process of modeling the strategic interaction between two or more players in a situation containing set rules and outcomes. While used in a number of disciplines, game theory is most notably used as a tool within the study of economics. The economic application of game theory can be a valuable tool to aide in the fundamental analysis of industries, sectors and any strategic interaction between two or more firms. Here, we'll take an introductory look at game theory and the terms involved, and introduce you to a simple method of solving games, called backwards induction.

<h5>Definitions</h5>
Any time we have a situation with two or more players that involves known payouts or quantifiable consequences, we can use game theory to help determine the most likely outcomes. 
Let's start out by defining a few terms commonly used in the study of game theory:
<p>

*  ***Game: *** Any set of circumstances that has a result dependent on the actions of two of more decision makers ("players")
*  ***Players: *** A strategic decision maker within the context of the game
*  ***Strategy: *** A complete plan of action a player will take given the set of circumstances that might arise within the game
*  ***Payoff: *** The payout a player receives from arriving at a particular outcome. The payout can be in any quantifiable form, from dollars to utility.
*  ***Information Set: *** The information available at a given point in the game. The term information set is most usually applied when the game has a sequential component.
*  ***Equilibrium: *** The point in a game where both players have made their decisions and an outcome is reached.


<h5>Assumptions</h5>
As with any concept in economics, there is the assumption of rationality. There is also an assumption of maximization. It is assumed that players within the game are rational and will strive to maximize their payoffs in the game. 

<p>

When examining games that are already set up, it is assumed on your behalf that the payouts listed include the sum of all payoffs that are associated with that outcome. This will exclude any "what if" questions that may arise.

<p>

The number of players in a game can theoretically be infinite, but most games will be put into the context of <b>two players</b>. One of the simplest games is a sequential game involving two players.

  
  
### Matrix Games

<h5>The Matrix Form of a 2-Player Game</h5>


* Assume that each player has a finite set of actions to choose from.
* In the matrix form of a 2-player game, each row corresponds to an
	action of Player 1 and each column corresponds to an action of
	Player 2.
* Each cell of the payoff matrix is associated with a payoff vector.
	The $\LARGE i-$th component of this vector gives the payoff to Player $\LARGE i$.

-------------------------------------
#### Videos 

* <a href=" https://youtu.be/3JDpYI1fsIA">Game Theory: Optimal Strategies and Value Of A 2x2 Game</a>

### Prisoner's Dilemna

<h5> Prisoner's Dilemna</h5>

### Dominance
In game theory, dominance occurs when one strategy is better than another strategy for one player, no matter how that player's opponents may play. Many simple games can be solved using dominance. The opposite, ***intransitivity***, occurs in games where one strategy may be better or worse than another strategy for one player, depending on how the player's opponents may play.

<h4>Terminology</h4>
When a player tries to choose the ``best" strategy among a multitude of options, that player may compare two strategies A and B to see which one is better. The result of the comparison is one of:

*  B dominates A: choosing B always gives as good as or a better outcome than choosing A. There are 2 possibilities:

*  B strictly dominates A: choosing B always gives a better outcome than choosing A, no matter what the other player(s) do.
*  B weakly dominates A: There is at least one set of opponents' action for which B is superior, and all other sets of opponents' actions give B the same payoff as A.

*  B and A are intransitive: B neither dominates, nor is dominated by, A. Choosing A is better in some cases, while choosing B is better in other cases, depending on exactly how the opponent chooses to play. \\ \textit{For example, B is ``throw rock" while A is "throw scissors" in Rock, Paper, Scissors.}
*  B is dominated by A: choosing B never gives a better outcome than choosing A, no matter what the other player(s) do. There are 2 possibilities:

*  B is weakly dominated by A: There is at least one set of opponents' actions for which B gives a worse outcome than A, while all other sets of opponents' actions give A the same payoff as B. (Strategy A weakly dominates B).
*  B is strictly dominated by A: choosing B always gives a worse outcome than choosing A, no matter what the other player(s) do. (Strategy A strictly dominates B).

This notion can be generalized beyond the comparison of two strategies.


*  Strategy B is strictly dominant if strategy B strictly dominates every other possible strategy.
*  Strategy B is weakly dominant if strategy B dominates all other strategies, but some (or all) strategies are only weakly dominated by B.
*  Strategy B is strictly dominated if some other strategy exists that strictly dominates B.
*  Strategy B is weakly dominated if some other strategy exists that weakly dominates B.

### Nash Equilibrium

Nash equilibrium is a solution concept of a non-cooperative game involving two or more players in which each player is assumed to know the equilibrium strategies of the other players, and no player has anything to gain by changing only their own strategy.

If each player has chosen a strategy and no player can benefit by changing strategies while the other players keep theirs unchanged, then the current set of strategy choices and the corresponding payoffs constitutes a Nash equilibrium. 


* Nash Equilibrium recommends a strategy to each player that the player cannot improve upon unilaterally, as long as the other players follow the recommendation.
* Since the other players are assumed to be rational, it is reasonable to expect the opponents to follow the recommendation as well.


<h5>Informal definition</h5>


* Informally, a strategy profile is a Nash equilibrium if no player can do better by unilaterally changing their strategy. To see what this means, imagine that each player is told the strategies of the others. Suppose then that each player asks themselves: *"Knowing the strategies of the other players, and treating the strategies of the other players as set in stone, can I benefit by changing my strategy?"*

* If any player could answer ``Yes", then that set of strategies is not a Nash equilibrium. But if every player prefers not to switch (or is indifferent between switching and not) then the strategy profile is a Nash equilibrium. Thus, each strategy in a Nash equilibrium is a best response to all other strategies in that equilibrium.

* The Nash equilibrium may sometimes appear non-rational in a third-person perspective. This is because it may happen that a Nash equilibrium is not Pareto optimal.

* The Nash equilibrium may also have non-rational consequences in sequential games because players may "threaten" each other with non-rational moves. For such games the subgame perfect Nash equilibrium may be more meaningful as a tool of analysis.

* Nash Equilibrium can also be thought of as ``no regrets," in the sense that once a decision is made, the player will have no regrets concerning decisions considering the consequences.
 
* The Nash Equilibrium is reached over time, in most cases. However, once the Nash Equilibrium is reached, it will becoming self-enforcing. 


### Nash Equilibtrium