Random Variables {data-navmenu="Random Variables"}
===========================================================

Column {.tabset}
-----------------------------------


### Random Variables

* <a href = "https://youtu.be/HRINuaUvGiY/"> Continuous Random Variables - Worked Example </a>
* <a href = "https://youtu.be/lxQEM8J8VrU/"> Random Variables: Conditional Expectation </a>

* <a href = "https://youtu.be/FdUo59EtA9Q/">Random Variables - Worked Example></a>

### Joint Random Variables 

* <a href = "https://youtu.be/jGzLUVFUgQ4/">Joint Random Variables - Worked Example<./a>


### Continuous Random Variables


* <a href = "https://youtu.be/LfJbK0jYh3M/"> Continuous Random Variables - Worked Example 1 </a>

* <a href = "https://youtu.be/QR4xS_WsCPA/"> Continuous Random Variable - Worked Example 2 </a>

* <a href = "https://youtu.be/N3oXRf2_Vmo/"> Continuous Random Variables - Worked Example 3</a>

* <a href = "https://youtu.be/rodfSPYXdh8/">Continuous Random Variable -  Worked Example 4 </a>



* <a href="https://youtu.be/QR4xS_WsCPA/">	Continuous Random Variable - Worked Example 2	</a>	
* <a href="https://youtu.be/rodfSPYXdh8/">	Continuous Random Variable Worked Example	</a>	
* <a href="https://youtu.be/HRINuaUvGiY/">	Continuous Random Variables -  Worked Example	</a>	
* <a href="https://youtu.be/LfJbK0jYh3M/">	Continuous Random Variables -  Worked Example 1	</a>	
* <a href="https://youtu.be/N3oXRf2_Vmo/">	Continuous Random Variables Worked Example	</a>	



### Random Variables


* <a href="https://youtu.be/BT67xUT8KGI/">	Random Variable Calculations	</a>	
* <a href="https://youtu.be/rJGWcfBD-EI/">	Random Variables - Mixed Probability Distributions	</a>	
* <a href="https://youtu.be/FdUo59EtA9Q/">	Random Variables - Worked Example	</a>	
* <a href="https://youtu.be/lxQEM8J8VrU/">	Random Variables: Conditional Expectation	</a>	
* <a href="https://youtu.be/aceFFyJCT4k/">	Random Variables: Cumulative Distributions Functions of Maxima and Minima	</a>	
* <a href="https://youtu.be/NGIUtX8OojA/">	Probability Density Functions of Continuous RVs - Worked Example	</a>	
* <a href="https://youtu.be/I-2iuiWwg8g/">	Properties of Random Variables (Law of Total Variance)	</a>	
* <a href="https://youtu.be/Rgi--7ScoUk/">	Sum and Difference of Random Variables	</a>	
* <a href="https://youtu.be/OBIUmaHGgfA/">	Sum Of Uniform Random Variables	</a>	
* <a href="https://youtu.be/nWEQlEqjLeQ/">	Median of A Random Variable	</a>	



### Combinations of Random Variables

* <a href = "https://youtu.be/UVukG1mRN_8/">Correlation Of Random Variables </a>
* <a href = "https://youtu.be/Rgi--7ScoUk/">Sum and Difference of Random Variables</a>
* <a href = "https://youtu.be/BT67xUT8KGI/">Random Variable Calculations</a>
* <a href = "https://youtu.be/UVukG1mRN_8/">Correlation Of Random Variables</a>


### Joint Random Variables

* <a href="https://www.youtube.com/embed/1yhu2Bmx7xw" >Joint Random Variables - Worked Example	</a>	
* <a href="https://www.youtube.com/embed/Xvq3RTCvd2g" >Joint Distribution of Discrete Random Variables</a>
* <a href="https://www.youtube.com/embed/8dLpooHUP4A" >Computing Covariance</a>
* <a href="https://www.youtube.com/embed/dgk5fJ3VjKI" >Joint Distribution of Discrete Random Variables</a>
* <a href="https://www.youtube.com/embed/ngIcXIrxEmU" >Computing Covariance </a>

### Introduction to Random Variables


*  An experiment is any process that generates will defined outcomes.
*  The outcome of an experiment need not be a number, for example, the outcome when a coin is tossed can be `heads' or `tails'. * 
	However, we often want to represent outcomes as numbers. 
*  We can describe the outcomes of an experiment using numbers and this numerical description is called a random variable.	
*  A random variable is a numerical description of the outcome of an experiment.
* 

A ***random variable*** is a function that associates a unique numerical value with every outcome of an experiment.
*  The value of the random variable will vary from trial to trial as the experiment is repeated.
*  Numeric values can be assigned to outcomes that are not usually considered numeric. 
*  For example, we could assign a `head' a value of $0$, and a `tail' a value of $1$, or vice versa.
*  Random variables can be classified as discrete or continuous, depending on the numerical values they may take.

<p>

#### What Are Random Variables

There are two types of random variable - discrete and continuous. The distinction between both types will be important later on in the course.

<p>
<h5>Examples</h5>

*   A coin is tossed ten times. The random variable X is the number of tails that are noted.
X can only take the values $\{0, 1, ..., 10\}$, so $X$ is a discrete random variable.
*   A light bulb is burned until it burns out. The random variable Y is its lifetime in hours.
Y can take any positive real value, so Y is a continuous random variable.

#### Discrete Random Variable

*   A discrete random variable is one which may take on only a countable number of distinct values such as $\{0, 1, 2, 3, 4, ... \}$.

* Discrete random variables are usually (but not necessarily) counts. 

* If a random variable can take only a finite number of distinct values, then it must be discrete. 

* Examples of discrete random variables include the number of children in a family, the Friday night attendance at a cinema, the number of patients in a doctor's surgery, the number of defective light bulbs in a box of ten.


<p>


#### Continuous Random Variable
 
*  A random variable that may assume any numerical value in an interval or collection of intervals is called a continuous random variable.
* 
A continuous random variable is one which takes an infinite number of possible values. *  Continuous random variables are usually measurements. *  Examples include height, weight, the amount of sugar in an orange, the time required to run a computer simulation. 
<p>

If X is a continuous random variable then we can say that the probability of obtaining a *precise* value $x$ is infinitely small, i.e. close to zero.

\[P(X=x) \approx 0 \]

Consequently, for continuous random variables (only),  $P(X \leq x)$ and $P(X < x)$ can be used interchangeably.

\[P(X \leq x) \approx P(X < x) \]

