The Paired t-test {data-navmenu="Paired Procedures"}
===========================================================

Column {.tabset}
-----------------------------------

### The Paired t-test
A paired t-test is used to compare two population means where you have two samples in
which observations in one sample can be paired with observations in the other sample.\\

Examples of where this might occur are:

*  Before-and-after observations on the same subjects (e.g. students’ diagnostic test
results before and after a particular module or course).
*  A comparison of two different methods of measurement or two different treatments
where the measurements/treatments are applied to the \textbf{\emph{same}} subjects.


<h4> The Paired t-test </h4>

*  We will often be required to compute the case-wise differences, the average of those differences and the standard deviation of those difference.

*  The mean difference for a set of differences between paired observations is
\[ \bar{d} = {\sum d_i \over n} \]

*  The computational formula for the standard deviation of the differences
between paired observations is
\[s_d = \sqrt{ {\sum d_i^2 - n\bar{d}^2 \over n-1}}\]
*  It is nearly always a small sample test.



*  $\mu_d$ mean value for the population of differences.
*  The null hypothesis is that that $\mu_d = 0$
*  Given $\bar{d}$ mean value for the sample of differences, and $s_d$ standard deviation of the differences for the paired sample data, we can compute this test in the same manner as a one-sample test for the mean



### Procedures


To test the null hypothesis that the true mean difference is zero, the procedure is as
follows:

1. Calculate the difference $(di = y_i − x_i)$ between the two observations on each pair,
making sure you distinguish between positive and negative differences.
2. Calculate the mean difference, $\bar{d}$.


3. Calculate the standard deviation of the differences, $s_d$, and use this to calculate the
standard error of the mean difference, $SE(\bar{d}) = {s_d \over \sqrt{n}}$

4. Calculate the t-statistic, which is given by $ T ={ \bar{d} \over SE(\bar{d})}$.

Under the null hypothesis, this statistic follows a t-distribution with $n − 1$ degrees of freedom.

}