Hypergeometric Distribution {data-navmenu="Discrete Distributions"}
=====================================

Column {.tabset}
-------------------------------------------------

### Hypergeometric Distribution

#### Probability mass function

The following conditions characterize the hypergeometric distribution:

*    The result of each draw (the elements of the population being sampled) can be classified into one of two mutually exclusive categories (e.g. Pass/Fail or Employed/Unemployed).
*    The probability of a success changes on each draw, as each draw decreases the population (sampling without replacement from a finite population).

A random variable ${\displaystyle X}$ follows the hypergeometric distribution if its probability mass function (pmf) is given by

\[ {\displaystyle p_{X}(k)=\Pr(X=k)={\frac {{\binom {K}{k}}{\binom {N-K}{n-k}}}{\binom {N}{n}}},}\]
where

* $N$ is the population size,
* $K$ is the number of success states in the population,
* $n$ is the number of draws (i.e. quantity drawn in each trial),
* $k$ is the number of observed successes,
* ${\textstyle \textstyle {a \choose b}}$ is a binomial coefficient.


### Videos 
<h5> Hypergeometric Distribution </h5>

* <a href="https://youtu.be/ay-Y_SUslP8/">	Hypergeometric Distribution - Worked Example	</a>	

