Poisson Approximation of the Binomial {data-navmenu="Approximations"}
=====================================

Column {.tabset}
-------------------------------------------------


<h4>Poisson Approximation of the Binomial</h4>


*  The Poisson distribution can sometimes be used to approximate the
binomial distribution
*  When the number of observations n is large, and the success probability
p is small, the $Bin(n,p)$ distribution approaches the Poisson distribution
with the parameter given by $m = np$.
*  This is useful since the computations involved in calculating binomial
probabilities are greatly reduced.
*  As a rule of thumb, n should be greater than 50 with p very small, such
that np should be less than 5.
*  We set = np (other notation $m = np$)  and use the Poisson tables.
*  If the value of p is very high, the definition of what constitutes a
``success" or ``failure" can be switched.


### Poisson Approximation: Example


*  Suppose we sample 1000 items from a production line that is producing, on
average, $0.1\%$ defective components.
*  Using the binomial distribution, the probability of exactly 3 defective items in
our sample is
\[P(X = 3) = ^{1000}C_{3} \times 0.001^{3} \times 0.999^{997}\]




*  Lets compute each of the component terms individually.


* [$\ast$] $^{1000}C_{3}$
\[^{1000}C_{3} = \frac{1000 \times 999 \times 998}{3 \times 2 \times 1} = 166,167,000\]
* [$\ast$] $0.001^3$
\[0.001^3 = 0.000000001\]
* [$\ast$] $0.999^{997}$
\[0.999^{997} = 0.36880\]



*  Multiply these three values to compute the binomial probability
$P(X = 3) = 0.06128$



\subsection{Using the Poisson Approximation (Same Example As previous)}

*  Lets use the Poisson distribution to approximate a solution.
*  First check that $n \geq 50$ and $np < 5$ (Yes to both).
*  We choose as our parameter value $m = np = 1000 \times 0.001 = 1$

\[P(X = 3) = \frac{e^{-1} \times 1^3}{3!} = \frac{e^{-1}}{6} = \frac{0.36787}{6} = 0.06131 \]
Compare this answer with the Binomial probability
P(X = 3) = 0.06128.
Very good approximation, with much less computation effort.


#### Poisson Approximation of the Binomial


*  The Poisson distribution can sometimes be used to approximate the
binomial distribution
*  When the number of observations n is large, and the success probability
p is small, the $Bin(n,p)$ distribution approaches the Poisson distribution
with the parameter given by $m = np$.
*  This is useful since the computations involved in calculating binomial
probabilities are greatly reduced.
*  As a rule of thumb, n should be greater than 50 with p very small, such
that np should be less than 5.
*  If the value of p is very high, the definition of what constitutes a
``success" or ``failure" can be switched.

<p>

%---------------------------------------------------------------------%

#### Poisson Approximation: Example}


*  Suppose we sample 1000 items from a production line that is producing, on
average, $0.1\%$ defective components.
*  Using the binomial distribution, the probability of exactly 3 defective items in
our sample is
\[P(X = 3) = ^{1000}C_{3} \times 0.001^{3} \times 0.999^{997}\]

<p>

%---------------------------------------------------------------------%

#### Poisson Approximation: Example}
Lets compute each of the component terms individually.


*  $^{1000}C_{3}$
\[^{1000}C_{3} = \frac{1000 \times 999 \times 998}{3 \times 2 \times 1} = 166,167,000\]
*  $0.001^3$
\[0.001^3 = 0.000000001\]
*  $0.999^{997}$
\[0.999^{997} = 0.36880\]



Multiply these three values to compute the binomial probability
$P(X = 3) = 0.06128$
<p>


#### Poisson Approximation: Example}

*  Lets use the Poisson distribution to approximate a solution.
*  First check that $n \geq 50$ and $np < 5$ (Yes to both).
*  We choose as our parameter value $m = np = 1000 \times 0.001 = 1$

\[P(X = 3) = \frac{e^{-1} \times 1^3}{3!} = \frac{e^{-1}}{6} = \frac{0.36787}{6} = 0.06131 \]
Compare this answer with the Binomial probability
P(X = 3) = 0.06128.
Very good approximation, with much less computation effort.




### Poisson Approximation 
The Poisson Approximation of the binomial ditribution

Example

\[P(X \geq 2) = 1 - (0.134+0.27) = 0.596\]

\[P(X=1) = 200 0.01 0.99 199\]

\[P(X=1) = 0.270\]


Poisson Approximaitions


\[X \sim \mbox{Binomial}(200, 0.01) \]


P(X= k)=e-kk!




\[P(X \geq 2) = 1- (0.135+0.27) = 0.595\]

%http://www.stats.gla.ac.uk/steps/glossary/hypothesis_testing.html




%======================================================================================= %
%--------------------------------------------%

\noindent \textbf{The Poisson Distribution}
{

*  The \textbf{Poisson mean} $\lambda$ (pronounced `lambda') is the expected number of occurrences per unit space / unit period.
*  (Remark:  Some texts will use the notation $m$ rather than $\lambda$)




Probability Density Function

\[P(X=k) = \frac{e^{m!}}{k!}\]
}




%========================================================%
Question 6 : Poisson approximation of the Binomial Distribution



binomial parameters 
number of trialsn =100
probability of success  p = 0.01

from binomial tables (MB1)

complement P ( X $\geq 2) = 0.2642$

therefore answer is P ( $X \leq 1) = 0.7358$






\subsection{Poisson }

*  M=15
(1/2 hour or 30 minutes)

*  5 minute period 
m=2.5 

*  X : No of arrivals

*  P(X=0) when M = 2.5

\[P(X=0) = 1 - P(X \geq 1) (Complement)\]
\[= 1 - 0.9179\]
\[= 0.0821\]







%========================================================%
Question 6 : Poisson approximation of the Binomial Distribution


*  binomial parameters 
*  number of trialsn =100
*  probability of success  p = 0.01

from binomial tables (MB1)

*  complement P ( X $\geq 2) = 0.2642$

*  therefore answer is P ( $X \leq 1) = 0.7358$



%==============================================================================% 


% {Poisson Random Variables}
% \noindent\textbf{Question:}\\
% Suppose that random variable X follows a Poisson distribution with rate parameter \texttt{\textbf{L}}. \\
% If we increase the value of \texttt{\textbf{L}}, which of the following is true?







\end{document}
