Poisson Process {data-navmenu="Poisson Distrubition"}
=====================================

Column {.tabset}
-------------------------------------------------

### Poisson Process

#### Characteristics of a Poisson Experiment
A Poisson experiment is a statistical experiment that has the following properties:

*  The experiment results in outcomes that can be classified as successes or failures.
*  The average number of successes (m) that occurs in a specified region is known.
*  The probability that a success will occur is proportional to the size of the region.
*  The probability that a success will occur in an extremely small region is virtually zero.

Note that the specified region could take many forms. For instance, it could be a length, an area, a volume, a period of time, etc.

<p>


#### The Poisson Probability Distribution}
Consider cars passing a point on a rarely used country road. Is this a Poisson Random Variable?
Suppose
\begin{enumerate}
*  Arrivals occur at an average rate of $m$ cars per unit time.
*  The probability of an arrival in an interval of length k
is constant.
*  The number of arrivals in two non-overlapping
intervals of time are independent.
\end{enumerate}
This would be an appropriate use of the Poisson Distribution.
<p>


#### Changing the unit time.


*  The number of arrivals, X, in an interval of length $t$ has a
Poisson distribution with parameter $\mu = mt$.
*  $m$ is the expected number of arrivals in a unit time period.
*  $\mu$ is the expected number of arrivals in a time period $t$, that is different from the unit time period.
*  Put simply : if we change the time period in question, we adjust the Poisson mean accordingly.
*  If 10 occurrences are expected in 1 hour, then 5 are expected in 30 minutes. Likewise, 20 occurrences are expected in 2 hours, and so on.
*  (Remark : we will not use $\mu$ in this context anymore).

<p>


#### Knowing which distribution to use}

*  For the end of semester examination, you will be required to know when it is appropriate to use the Poisson distribution, and when to use the binomial distribution.
*  Recall the key parameters of each distribution.
*  Binomial : number of \textbf{\emph{successes}} in $n$ \textbf{\emph{independent trials}}.
*  Poisson : number of \textbf{\emph{occurrences}} in a \textbf{\emph{unit space}}.

<p>


#### Poisson Distribution}
A Poisson random variable is the number of successes that result from a Poisson experiment.
 
The probability distribution of a Poisson random variable is called a Poisson distribution.

Given the mean number of successes ($m$) that occur in a specified region, we can compute the Poisson probability based on the following formula:

<p>


#### The Poisson Probability Distribution}

*  The number of occurrences in a unit period (or space)
*  The expected number of occurrences is $m$



#### Poisson Formulae}
The probability that there will be $k$ occurences in a unit time period is denoted $P(X=k)$, and is computed as follows.
<p>
\[ P(X = k)=\frac{m^k e^{-m}}{k!} \]


#### Poisson Formulae}
Given that there is on average 2 occurences per hour, what is the probability of no occurences in the next hour? \\ i.e. Compute $P(X=0)$ given that $m=2$
<p>
\[ P(X = 0)=\frac{2^0 e^{-2}}{0!} \]
\normalsize

*  $2^0$ = 1
*  $0!$ = 1

The equation reduces to 
\[ P(X = 0)=e^{-2} = 0.1353\]


#### Poisson Formulae}
What is the probability of one occurences in the next hour? \\ i.e. Compute $P(X=1)$ given that $m=2$
<p>
\[ P(X = 1)=\frac{2^1 e^{-2}}{1!} \]
\normalsize

*  $2^1$ = 2
*  $1!$ = 1

The equation reduces to
\[ P(X = 1) = 2 \times e^{-2} = 0.2706\]
}
%---------------------------------------------------------------------------%

\end{document} 