
Small Samples and the t- distribution {data-navmenu="Inference Procedures"}
==============================================================


Column {.tabset}
----------------------------------


### The Student t- distribution

* The $t$ distribution is the appropriate basis for
determining the standardized test statistic when the sampling
distribution of the mean is normally distributed but $s$ is not
known. 
* The sampling distribution can be assumed to be normal
either because the population is normal or because the sample is
large enough to invoke the central limit theorem.  

* The $t$
distribution is required when the sample is small ($n < 30$). For
larger samples, normal approximation can be used. 
* For the critical
value approach, the procedure is identical to that described of the normal distribution, except for the use of $t$
instead of z as the test statistic.

### Quantiles

The quantile function is the inverse of the cumulative
distribution function. The p-quantile is the value with the
property that there is probability p of getting a value less than
or equal to it. The median is by definition the 50\% quantile.


Theoretical quantiles are commonly used for the calculation of
confidence intervals and for power calculations in connection with
designing and dimensioning experiments.
